stages:
  - build
  - deploy

build_dev:
  image: node:16.20.2
  stage: build
  script:
    - npm install -g @angular/cli@11.2.14
    - npm install || true
    - npm install --legacy-peer-deps
    - ng build --configuration=test
  artifacts:
    paths:
      - dist/
  only:
    - develop
build_test:
  image: node:16.20.2
  stage: build
  script:
    - npm install -g @angular/cli@11.2.14
    - npm install || true
    - npm install --legacy-peer-deps
    - ng build --configuration=test
  artifacts:
    paths:
      - dist/
  only:
    - test
build_prod:
  image: node:16.20.2
  stage: build
  script:
    - npm install -g @angular/cli@11.2.14
    - npm install || true
    - npm install --legacy-peer-deps
    - ng build --configuration=production
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy_testing:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - scp -r $CI_PROJECT_DIR/dist/my-app/* $SERVER_USER@$SERVER_HOST:/var/www/html/platform/test/frontend/dist/my-app
  after_script:
    - rm -rf ~/.ssh
  only:
    - test

deploy_development:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - scp -r $CI_PROJECT_DIR/dist/my-app/* $SERVER_USER@$SERVER_HOST:/var/www/html/platform/dev/frontend/dist/my-app
  after_script:
    - rm -rf ~/.ssh
  only:
    - develop

deploy_production:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - scp -r $CI_PROJECT_DIR/dist/my-app/* $SERVER_USER@$SERVER_HOST:/var/www/html/platform/prod/frontend/dist/my-app
  after_script:
    - rm -rf ~/.ssh
  only:
    - master
