stages:
  - build
  - deploy

build_dev:
  image: node:16.20.2
  stage: build
  script:
    - npm install --legacy-peer-deps
    - ng build --configuration=development
  artifacts:
    paths:
      - dist/
  only:
    - develop
build_test:
  image: node:16.20.2
  stage: build
  script:
    - npm install --legacy-peer-deps
    - ng build --configuration=test
  artifacts:
    paths:
      - dist/
  only:
    - test
build_prod:
  image: node:16.20.2
  stage: build
  script:
    - npm install --legacy-peer-deps
    - ng build --configuration=production
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy_testing:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /var/www/html/platform/test/frontend && git pull origin test && exit"
  after_script:
    - rm -rf ~/.ssh
  only:
    - test

deploy_development:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /var/www/html/platform/dev/frontend && git pull origin develop && exit"
  after_script:
    - rm -rf ~/.ssh
  only:
    - develop

deploy_production:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /var/www/html/platform/prod/frontend && git pull origin master && exit"
  after_script:
    - rm -rf ~/.ssh
  only:
    - master
