export interface Alert {
  nr?: number;
  id: string,
  tipo: string,
  nombre?: string,
  activo: string,
  imei: string,
  valor_verificado: string,
  array_geocirc: string,
  sistema_notificacion: string,
  notificacion_email: string,
  notificacion_direcion_email?: string,
  notificacion_sms: boolean,
  notificacion_numero_sms?: string,
  comando_enviado: boolean,
  tipo_comando?: string,
  cadena_comando?: string,
  usuario_id: string,
  fecha_desde: string,
  fecha_hasta: string,
  bol_fecha_caducidad: boolean,
  fecha_desdex: string,
  fecha_hastax: string,
  bol_duracion_parada: boolean,
  duracion_parada: string,
  duracion_formato_parada: string,
  int_h_mantenimiento_establecida: string,
  int_h_mantenimiento_antelacion: string,
  bol_fijar_tiempo: boolean,
  tiempo_limite_infraccion: string,
  bol_fijar_velocidad: boolean,
  velocidad_limite_infraccion: string,
  sonido_sistema_bol?:boolean,
  notificacion_email_bol?:boolean,
  activo_bol?:boolean
}